<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:trt="http://www.onvif.org/ver10/media/wsdl"
    xmlns:tt="http://www.onvif.org/ver10/schema"
    xmlns:ter="http://www.onvif.org/ver10/error"
    targetNamespace="http://www.onvif.org/ver10/media/wsdl">

    <wsdl:types>
        <xs:schema targetNamespace="http://www.onvif.org/ver10/media/wsdl" elementFormDefault="qualified">
            <xs:import namespace="http://www.onvif.org/ver10/schema" schemaLocation="types.xsd"/>
            <xs:complexType name="ProfileCapabilities">
                <xs:sequence/>
                <xs:attribute name="MaximumNumberOfProfiles" type="xs:int"/>
                <xs:anyAttribute processContents="lax"/>
            </xs:complexType>

            <xs:complexType name="StreamingCapabilities">
                <xs:sequence/>
                <xs:attribute name="RTPMulticast" type="xs:boolean"/>
                <xs:attribute name="RTP_TCP" type="xs:boolean"/>
                <xs:attribute name="RTP_RTSP_TCP" type="xs:boolean"/>
                <xs:attribute name="NonAggregateControl" type="xs:boolean"/>
                <xs:attribute name="NoRTSPStreaming" type="xs:boolean"/>
                <xs:anyAttribute processContents="lax"/>
            </xs:complexType>

            <xs:complexType name="Capabilities">
                <xs:sequence>
                    <xs:element name="ProfileCapabilities" type="trt:ProfileCapabilities"/>
                    <xs:element name="StreamingCapabilities" type="trt:StreamingCapabilities"/>
                    <xs:any namespace="##any" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
                </xs:sequence>
                <xs:attribute name="SnapshotUri" type="xs:boolean"/>
                <xs:attribute name="Rotation" type="xs:boolean"/>
                <xs:attribute name="VideoSourceMode" type="xs:boolean"/>
                <xs:attribute name="OSD" type="xs:boolean"/>
                <xs:anyAttribute processContents="lax"/>
            </xs:complexType>

            <xs:element name="GetServiceCapabilities">
                <xs:complexType/>
            </xs:element>
            <xs:element name="GetServiceCapabilitiesResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Capabilities" type="trt:Capabilities"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="GetProfiles">
                <xs:complexType/>
            </xs:element>
            <xs:element name="GetProfilesResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Profiles" type="tt:Profile" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="GetStreamUri">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="StreamSetup" type="tt:StreamSetup"/>
                        <xs:element name="ProfileToken" type="tt:ReferenceToken"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="GetStreamUriResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="MediaUri" type="tt:MediaUri"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="GetSnapshotUri">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="ProfileToken" type="tt:ReferenceToken"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="GetSnapshotUriResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="MediaUri" type="tt:MediaUri"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="GetVideoSources">
                <xs:complexType/>
            </xs:element>
            <xs:element name="GetVideoSourcesResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="VideoSources" type="tt:VideoSource" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="GetVideoSourceConfiguration">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="ConfigurationToken" type="tt:ReferenceToken"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="GetVideoSourceConfigurationResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="VideoSourceConfiguration" type="tt:VideoSourceConfiguration"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="GetVideoEncoderConfiguration">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="ConfigurationToken" type="tt:ReferenceToken"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="GetVideoEncoderConfigurationResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="VideoEncoderConfiguration" type="tt:VideoEncoderConfiguration"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="GetProfile">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="ProfileToken" type="tt:ReferenceToken"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="GetProfileResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Profile" type="tt:Profile"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="GetVideoSourceConfigurations">
                <xs:complexType/>
            </xs:element>
            <xs:element name="GetVideoSourceConfigurationsResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Configurations" type="tt:VideoSourceConfiguration" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="GetCompatibleVideoSourceConfigurations">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="ProfileToken" type="tt:ReferenceToken"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="GetCompatibleVideoSourceConfigurationsResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Configurations" type="tt:VideoSourceConfiguration" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="GetVideoEncoderConfigurations">
                <xs:complexType/>
            </xs:element>
            <xs:element name="GetVideoEncoderConfigurationsResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Configurations" type="tt:VideoEncoderConfiguration" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="GetCompatibleVideoEncoderConfigurations">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="ProfileToken" type="tt:ReferenceToken"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="GetCompatibleVideoEncoderConfigurationsResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Configurations" type="tt:VideoEncoderConfiguration" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="GetVideoEncoderConfigurationOptions">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="ConfigurationToken" type="tt:ReferenceToken" minOccurs="0"/>
                        <xs:element name="ProfileToken" type="tt:ReferenceToken" minOccurs="0"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="GetVideoEncoderConfigurationOptionsResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Options" type="tt:VideoEncoderConfigurationOptions"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:schema>
    </wsdl:types>

    <wsdl:message name="GetServiceCapabilitiesRequest">
        <wsdl:part name="parameters" element="trt:GetServiceCapabilities"/>
    </wsdl:message>
    <wsdl:message name="GetServiceCapabilitiesResponse">
        <wsdl:part name="parameters" element="trt:GetServiceCapabilitiesResponse"/>
    </wsdl:message>
    <wsdl:message name="GetProfilesRequest">
        <wsdl:part name="parameters" element="trt:GetProfiles"/>
    </wsdl:message>
    <wsdl:message name="GetProfilesResponse">
        <wsdl:part name="parameters" element="trt:GetProfilesResponse"/>
    </wsdl:message>
    <wsdl:message name="GetStreamUriRequest">
        <wsdl:part name="parameters" element="trt:GetStreamUri"/>
    </wsdl:message>
    <wsdl:message name="GetStreamUriResponse">
        <wsdl:part name="parameters" element="trt:GetStreamUriResponse"/>
    </wsdl:message>
    <wsdl:message name="GetSnapshotUriRequest">
        <wsdl:part name="parameters" element="trt:GetSnapshotUri"/>
    </wsdl:message>
    <wsdl:message name="GetSnapshotUriResponse">
        <wsdl:part name="parameters" element="trt:GetSnapshotUriResponse"/>
    </wsdl:message>
    <wsdl:message name="GetVideoSourcesRequest">
        <wsdl:part name="parameters" element="trt:GetVideoSources"/>
    </wsdl:message>
    <wsdl:message name="GetVideoSourcesResponse">
        <wsdl:part name="parameters" element="trt:GetVideoSourcesResponse"/>
    </wsdl:message>
    <wsdl:message name="GetVideoSourceConfigurationRequest">
        <wsdl:part name="parameters" element="trt:GetVideoSourceConfiguration"/>
    </wsdl:message>
    <wsdl:message name="GetVideoSourceConfigurationResponse">
        <wsdl:part name="parameters" element="trt:GetVideoSourceConfigurationResponse"/>
    </wsdl:message>
    <wsdl:message name="GetVideoEncoderConfigurationRequest">
        <wsdl:part name="parameters" element="trt:GetVideoEncoderConfiguration"/>
    </wsdl:message>
    <wsdl:message name="GetVideoEncoderConfigurationResponse">
        <wsdl:part name="parameters" element="trt:GetVideoEncoderConfigurationResponse"/>
    </wsdl:message>

    <wsdl:message name="GetProfileRequest"><wsdl:part name="parameters" element="trt:GetProfile"/></wsdl:message>
    <wsdl:message name="GetProfileResponse"><wsdl:part name="parameters" element="trt:GetProfileResponse"/></wsdl:message>
    <wsdl:message name="GetVideoSourceConfigurationsRequest"><wsdl:part name="parameters" element="trt:GetVideoSourceConfigurations"/></wsdl:message>
    <wsdl:message name="GetVideoSourceConfigurationsResponse"><wsdl:part name="parameters" element="trt:GetVideoSourceConfigurationsResponse"/></wsdl:message>
    <wsdl:message name="GetCompatibleVideoSourceConfigurationsRequest"><wsdl:part name="parameters" element="trt:GetCompatibleVideoSourceConfigurations"/></wsdl:message>
    <wsdl:message name="GetCompatibleVideoSourceConfigurationsResponse"><wsdl:part name="parameters" element="trt:GetCompatibleVideoSourceConfigurationsResponse"/></wsdl:message>
    <wsdl:message name="GetVideoEncoderConfigurationsRequest"><wsdl:part name="parameters" element="trt:GetVideoEncoderConfigurations"/></wsdl:message>
    <wsdl:message name="GetVideoEncoderConfigurationsResponse"><wsdl:part name="parameters" element="trt:GetVideoEncoderConfigurationsResponse"/></wsdl:message>
    <wsdl:message name="GetCompatibleVideoEncoderConfigurationsRequest"><wsdl:part name="parameters" element="trt:GetCompatibleVideoEncoderConfigurations"/></wsdl:message>
    <wsdl:message name="GetCompatibleVideoEncoderConfigurationsResponse"><wsdl:part name="parameters" element="trt:GetCompatibleVideoEncoderConfigurationsResponse"/></wsdl:message>
    <wsdl:message name="GetVideoEncoderConfigurationOptionsRequest"><wsdl:part name="parameters" element="trt:GetVideoEncoderConfigurationOptions"/></wsdl:message>
    <wsdl:message name="GetVideoEncoderConfigurationOptionsResponse"><wsdl:part name="parameters" element="trt:GetVideoEncoderConfigurationOptionsResponse"/></wsdl:message>

    <wsdl:portType name="MediaPort">
        <wsdl:operation name="GetServiceCapabilities">
            <wsdl:input message="trt:GetServiceCapabilitiesRequest"/>
            <wsdl:output message="trt:GetServiceCapabilitiesResponse"/>
        </wsdl:operation>
        <wsdl:operation name="GetProfiles">
            <wsdl:input message="trt:GetProfilesRequest"/>
            <wsdl:output message="trt:GetProfilesResponse"/>
        </wsdl:operation>
        <wsdl:operation name="GetStreamUri">
            <wsdl:input message="trt:GetStreamUriRequest"/>
            <wsdl:output message="trt:GetStreamUriResponse"/>
        </wsdl:operation>
        <wsdl:operation name="GetSnapshotUri">
            <wsdl:input message="trt:GetSnapshotUriRequest"/>
            <wsdl:output message="trt:GetSnapshotUriResponse"/>
        </wsdl:operation>
        <wsdl:operation name="GetVideoSources">
            <wsdl:input message="trt:GetVideoSourcesRequest"/>
            <wsdl:output message="trt:GetVideoSourcesResponse"/>
        </wsdl:operation>
        <wsdl:operation name="GetVideoSourceConfiguration">
            <wsdl:input message="trt:GetVideoSourceConfigurationRequest"/>
            <wsdl:output message="trt:GetVideoSourceConfigurationResponse"/>
        </wsdl:operation>
        <wsdl:operation name="GetVideoEncoderConfiguration">
            <wsdl:input message="trt:GetVideoEncoderConfigurationRequest"/>
            <wsdl:output message="trt:GetVideoEncoderConfigurationResponse"/>
        </wsdl:operation>
        <wsdl:operation name="GetProfile"><wsdl:input message="trt:GetProfileRequest"/><wsdl:output message="trt:GetProfileResponse"/></wsdl:operation>
        <wsdl:operation name="GetVideoSourceConfigurations"><wsdl:input message="trt:GetVideoSourceConfigurationsRequest"/><wsdl:output message="trt:GetVideoSourceConfigurationsResponse"/></wsdl:operation>
        <wsdl:operation name="GetCompatibleVideoSourceConfigurations"><wsdl:input message="trt:GetCompatibleVideoSourceConfigurationsRequest"/><wsdl:output message="trt:GetCompatibleVideoSourceConfigurationsResponse"/></wsdl:operation>
        <wsdl:operation name="GetVideoEncoderConfigurations"><wsdl:input message="trt:GetVideoEncoderConfigurationsRequest"/><wsdl:output message="trt:GetVideoEncoderConfigurationsResponse"/></wsdl:operation>
        <wsdl:operation name="GetCompatibleVideoEncoderConfigurations"><wsdl:input message="trt:GetCompatibleVideoEncoderConfigurationsRequest"/><wsdl:output message="trt:GetCompatibleVideoEncoderConfigurationsResponse"/></wsdl:operation>
        <wsdl:operation name="GetVideoEncoderConfigurationOptions"><wsdl:input message="trt:GetVideoEncoderConfigurationOptionsRequest"/><wsdl:output message="trt:GetVideoEncoderConfigurationOptionsResponse"/></wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="MediaBinding" type="trt:MediaPort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="GetServiceCapabilities">
            <soap:operation soapAction="http://www.onvif.org/ver10/media/wsdl/GetServiceCapabilities"/>
            <wsdl:input><soap:body use="literal"/></wsdl:input>
            <wsdl:output><soap:body use="literal"/></wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="GetProfiles">
            <soap:operation soapAction="http://www.onvif.org/ver10/media/wsdl/GetProfiles"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="GetStreamUri">
            <soap:operation soapAction="http://www.onvif.org/ver10/media/wsdl/GetStreamUri"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="GetSnapshotUri">
            <soap:operation soapAction="http://www.onvif.org/ver10/media/wsdl/GetSnapshotUri"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="GetVideoSources">
            <soap:operation soapAction="http://www.onvif.org/ver10/media/wsdl/GetVideoSources"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="GetVideoSourceConfiguration">
            <soap:operation soapAction="http://www.onvif.org/ver10/media/wsdl/GetVideoSourceConfiguration"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="GetVideoEncoderConfiguration">
            <soap:operation soapAction="http://www.onvif.org/ver10/media/wsdl/GetVideoEncoderConfiguration"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="GetProfile">
            <soap:operation soapAction="http://www.onvif.org/ver10/media/wsdl/GetProfile"/>
            <wsdl:input><soap:body use="literal"/></wsdl:input>
            <wsdl:output><soap:body use="literal"/></wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="GetVideoSourceConfigurations">
            <soap:operation soapAction="http://www.onvif.org/ver10/media/wsdl/GetVideoSourceConfigurations"/>
            <wsdl:input><soap:body use="literal"/></wsdl:input>
            <wsdl:output><soap:body use="literal"/></wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="GetCompatibleVideoSourceConfigurations">
            <soap:operation soapAction="http://www.onvif.org/ver10/media/wsdl/GetCompatibleVideoSourceConfigurations"/>
            <wsdl:input><soap:body use="literal"/></wsdl:input>
            <wsdl:output><soap:body use="literal"/></wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="GetVideoEncoderConfigurations">
            <soap:operation soapAction="http://www.onvif.org/ver10/media/wsdl/GetVideoEncoderConfigurations"/>
            <wsdl:input><soap:body use="literal"/></wsdl:input>
            <wsdl:output><soap:body use="literal"/></wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="GetCompatibleVideoEncoderConfigurations">
            <soap:operation soapAction="http://www.onvif.org/ver10/media/wsdl/GetCompatibleVideoEncoderConfigurations"/>
            <wsdl:input><soap:body use="literal"/></wsdl:input>
            <wsdl:output><soap:body use="literal"/></wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="GetVideoEncoderConfigurationOptions">
            <soap:operation soapAction="http://www.onvif.org/ver10/media/wsdl/GetVideoEncoderConfigurationOptions"/>
            <wsdl:input><soap:body use="literal"/></wsdl:input>
            <wsdl:output><soap:body use="literal"/></wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="MediaService">
        <wsdl:port name="MediaPort" binding="trt:MediaBinding">
            <soap:address location="http://0.0.0.0/onvif/media_service"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>